// Generated by scripts/generate-admin-config.mjs — do not edit, do not commit.
export const SUPABASE_URL = "https://obujvbiwqspdnewetgyi.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9idWp2Yml3cXNwZG5ld2V0Z3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5NDE2NzEsImV4cCI6MjA5ODUxNzY3MX0.GX4iOpfx9fdc-YPJx7QrgKPzOvNzxdy0MOWdbKh8tfk";
